### ISSUE TITLE
Markup and spelling errors

### ISSUE THREAD

**Issue by Alanaktion** [Phrostbyte21/BIGbigger#1]
There are a few errors in `index.html`:
- `<header>` should be within `<body>`
- `<form>` element was closed with `</div>` but should be `</form>`
- `<textarea>` should not have a `type` attribute
- `<button>` should not have an `input` attribute
- `<input type="number">` should only be used for literal numbers (_e.g._ integers), `type="tel"` should be used for phone number inputs

[See all validation errors and warnings](https://validator.w3.org/nu/?doc=https%3A%2F%2Fdetermined-bose-3ba81a.netlify.app%2F)

There are two spelling errors:
- "Transportation" is spelled incorrectly in `index.html`
- "Restaurant" is spelled incorrectly in `business.js`, `main.js`, and `index.html`

**Comment by Phrostbyte21** [comment]
Thanks for pointing those out! I missed a lot of this mistakes multiple times, apparently.
